### Data importation using Pandas Library

In [31]:
import pandas as pd

In [32]:
df = pd.read_csv("C:\\Users\\HomePC\\Downloads\\TB_outcomes_age_sex_2026-07-03.csv",
             index_col='country', 
            names=['country','iso2','iso3','iso_numceric','WHO_region','year','cohort_type',
                     'age_group','sex','total_patients_cohort','success','failure','deaths',
                     'lost_to_follow_up','not_evaluated','success_rate'])

In [33]:
df = df.drop(labels='country', axis=0)

### Standardization of Sex column

In [34]:
sex_full = []
for data in df['sex']:
    if data == 'f':
        sex_full.append('Female')
    elif data == 'm':
        sex_full.append('Male')
    elif data == 'a':
        sex_full.append('All sexes')

In [35]:
df['sex'] = sex_full

In [36]:
df

,iso2,iso3,iso_numceric,WHO_region,year,cohort_type,age_group,sex,total_patients_cohort,success,failure,deaths,lost_to_follow_up,not_evaluated,success_rate
country,,,,,,,,,,,,,,,
Afghanistan,AF,AFG,004,EMR,2018,newrel,0-14,All sexes,10461,10027,NaN,NaN,NaN,NaN,96
Albania,AL,ALB,008,EUR,2010,newrel,0-14,All sexes,18,17,0,0,0,1,94
Albania,AL,ALB,008,EUR,2011,newrel,0-14,All sexes,7,7,0,0,0,0,100
Albania,AL,ALB,008,EUR,2012,newrel,0-14,All sexes,3,3,0,0,0,0,100
Albania,AL,ALB,008,EUR,2013,newrel,0-14,All sexes,19,18,0,0,1,0,95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zimbabwe,ZW,ZWE,716,AFR,2021,newrel,a,Male,10475,9535,71,637,82,150,91
Zimbabwe,ZW,ZWE,716,AFR,2022,newrel,0-14,All sexes,1109,1082,NaN,NaN,NaN,NaN,98
Zimbabwe,ZW,ZWE,716,AFR,2023,newrel,0-14,All sexes,1136,1061,NaN,NaN,NaN,NaN,93
Zimbabwe,ZW,ZWE,716,AFR,2023,newrel,a,Female,6623,6463,25,100,30,5,98
Zimbabwe,ZW,ZWE,716,AFR,2023,newrel,a,Male,12540,11002,31,1237,221,49,88

### Standardization of Age group column

In [37]:
ages= []

for age in df['age_group']:
    if age == 'a':
        ages.append('All ages')
    else:
        ages.append(age)

In [38]:
df['age_group'] = ages

### Removal NaN Values

In [39]:
df.fillna(' ')

,iso2,iso3,iso_numceric,WHO_region,year,cohort_type,age_group,sex,total_patients_cohort,success,failure,deaths,lost_to_follow_up,not_evaluated,success_rate
country,,,,,,,,,,,,,,,
Afghanistan,AF,AFG,004,EMR,2018,newrel,0-14,All sexes,10461,10027,,,,,96
Albania,AL,ALB,008,EUR,2010,newrel,0-14,All sexes,18,17,0,0,0,1,94
Albania,AL,ALB,008,EUR,2011,newrel,0-14,All sexes,7,7,0,0,0,0,100
Albania,AL,ALB,008,EUR,2012,newrel,0-14,All sexes,3,3,0,0,0,0,100
Albania,AL,ALB,008,EUR,2013,newrel,0-14,All sexes,19,18,0,0,1,0,95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zimbabwe,ZW,ZWE,716,AFR,2021,newrel,All ages,Male,10475,9535,71,637,82,150,91
Zimbabwe,ZW,ZWE,716,AFR,2022,newrel,0-14,All sexes,1109,1082,,,,,98
Zimbabwe,ZW,ZWE,716,AFR,2023,newrel,0-14,All sexes,1136,1061,,,,,93
Zimbabwe,ZW,ZWE,716,AFR,2023,newrel,All ages,Female,6623,6463,25,100,30,5,98
Zimbabwe,ZW,ZWE,716,AFR,2023,newrel,All ages,Male,12540,11002,31,1237,221,49,88

### Columns correction to the right Datatype

In [40]:
df.info()

<class 'pandas.DataFrame'>
Index: 1607 entries, Afghanistan to Zimbabwe
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   iso2                   1591 non-null   str
 1   iso3                   1607 non-null   str
 2   iso_numceric           1607 non-null   str
 3   WHO_region             1607 non-null   str
 4   year                   1607 non-null   str
 5   cohort_type            1607 non-null   str
 6   age_group              1607 non-null   str
 7   sex                    1607 non-null   str
 8   total_patients_cohort  1607 non-null   str
 9   success                1588 non-null   str
 10  failure                1114 non-null   str
 11  deaths                 1117 non-null   str
 12  lost_to_follow_up      1118 non-null   str
 13  not_evaluated          1122 non-null   str
 14  success_rate           1467 non-null   str
dtypes: str(15)
memory usage: 200.9+ KB

In [41]:
df['total_patients_cohort'] = pd.to_numeric(df['total_patients_cohort'], errors='coerce')
df['success'] = pd.to_numeric(df['success'], errors='coerce')
df['failure'] = pd.to_numeric(df['failure'], errors='coerce')
df['deaths'] = pd.to_numeric(df['deaths'], errors='coerce')
df['lost_to_follow_up'] = pd.to_numeric(df['lost_to_follow_up'], errors='coerce')
df['not_evaluated'] = pd.to_numeric(df['total_patients_cohort'], errors='coerce')
df['success_rate'] = pd.to_numeric(df['success_rate'], errors='coerce')
df['year'] = pd.to_numeric(df['year'], errors='coerce')

In [42]:
df

,iso2,iso3,iso_numceric,WHO_region,year,cohort_type,age_group,sex,total_patients_cohort,success,failure,deaths,lost_to_follow_up,not_evaluated,success_rate
country,,,,,,,,,,,,,,,
Afghanistan,AF,AFG,004,EMR,2018,newrel,0-14,All sexes,10461,10027.0,NaN,NaN,NaN,10461,96.0
Albania,AL,ALB,008,EUR,2010,newrel,0-14,All sexes,18,17.0,0.0,0.0,0.0,18,94.0
Albania,AL,ALB,008,EUR,2011,newrel,0-14,All sexes,7,7.0,0.0,0.0,0.0,7,100.0
Albania,AL,ALB,008,EUR,2012,newrel,0-14,All sexes,3,3.0,0.0,0.0,0.0,3,100.0
Albania,AL,ALB,008,EUR,2013,newrel,0-14,All sexes,19,18.0,0.0,0.0,1.0,19,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zimbabwe,ZW,ZWE,716,AFR,2021,newrel,All ages,Male,10475,9535.0,71.0,637.0,82.0,10475,91.0
Zimbabwe,ZW,ZWE,716,AFR,2022,newrel,0-14,All sexes,1109,1082.0,NaN,NaN,NaN,1109,98.0
Zimbabwe,ZW,ZWE,716,AFR,2023,newrel,0-14,All sexes,1136,1061.0,NaN,NaN,NaN,1136,93.0
Zimbabwe,ZW,ZWE,716,AFR,2023,newrel,All ages,Female,6623,6463.0,25.0,100.0,30.0,6623,98.0
Zimbabwe,ZW,ZWE,716,AFR,2023,newrel,All ages,Male,12540,11002.0,31.0,1237.0,221.0,12540,88.0